apiVersion: v1
kind: Service
metadata:
  name: finance-db
  labels:
    app.kubernetes.io/name: finance-db
    app.kubernetes.io/part-of: finance
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: finance-db
  labels:
    kubernetes.io/service-name: finance-db
    app.kubernetes.io/name: finance-db
    app.kubernetes.io/part-of: finance
addressType: IPv4
ports:
  - name: postgres
    protocol: TCP
    port: 5432
endpoints:
  - addresses:
      - 192.168.0.13
